quarkus:
  http:
    port: 8081

  infinispan-client:
    server-list: localhost:11222
    auth-username: root
    auth-password: root
    auth-server-name: infinispan
    auth-realm: default
    client-intelligence: BASIC

  smallrye-openapi:
    path: /swagger
  swagger-ui.always-include: true
  swagger-ui.path: /public-api
mp:
  openapi:
    scan:
      disable: true