#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: redis
#spec:
#  selector:
#    matchLabels:
#      app: redis
#  replicas: 2
#  template:
#    metadata:
#      labels:
#        app: redis
#    spec:
#      containers:
#        - name: redis-api
#          imagePullPolicy: Never
#          image: redis:latest
#          ports:
#            - containerPort: 8082
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: redis
#spec:
#  type: NodePort
#  selector:
#    app: redis
#  ports:
#    - port: 8082
#      targetPort: 8082


apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-action-runner
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: velotio/action-runner-poc