quarkus:
  http:
    port: 8083
    auth:
      permission:
        authenticated:
          paths: /*
          policy: authenticated

  oidc:
    auth-server-url: http://localhost:8180/auth/realms/sample
    client-id: backend-service
    #    application-type: web-app
    credentials:
      secret: jWBCs4FpRInOEDZhiiL1FLxXvl9q7OMN

  keycloak:
    policy-enforcer:
      enable: true