quarkus:
  datasource:
    username: postgres
    password: 123456
    jdbc:
      url: jdbc:postgresql://localhost:5432/sample
  http:
    port: 8084

  hibernate-orm:
    database:
      generation: update
    #    sql-load-script: data.sql
    log:
      sql: true
  smallrye-openapi:
    path: /swagger
  swagger-ui.always-include: true
  swagger-ui.path: /public-api
mp:
  openapi:
    scan:
      disable: true
