# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set something
        run: eval $(minikube docker-env)
      - name: Build the Docker image
        run: docker build . --file .github/workflows/Dockerfile --tag quarkus-sample:v1
  deploy:
    needs: build
    runs-on:
      - self-hosted
    steps:
      - name: Set config for K8s
        run: kubectl apply -f .github/workflows/redis.yml --kubeconfig=/root/.kube/config
      - name: Deploy on kuber
        run: kubectl get pods --kubeconfig=/root/.kube/config
