apiVersion: apps/v1
kind: Deployment
metadata:
 name: qurkus-sample
spec:
 selector:
   matchLabels:
     app: qurkus-sample
 replicas: 2
 template:
   metadata:
     labels:
       app: qurkus-sample
   spec:
     containers:
       - name: qurkus-sample-api
         imagePullPolicy: Never
         image: qurkus-sample:v1
         ports:
           - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
 name: qurkus-sample
spec:
 type: NodePort
 selector:
   app: qurkus-sample
 ports:
   - port: 8082
     targetPort: 8082
