quarkus:
  http:
    port: 8082

  redis:
    hosts: redis://localhost:6379

  smallrye-openapi:
    path: /swagger
  swagger-ui.always-include: true
  swagger-ui.path: /public-api
mp:
  openapi:
    scan:
      disable: true
